### ISSUE TITLE
Refusing to install bigbluebot as a dependency of itself

### ISSUE THREAD

**Issue by shahidge4** [mconf/bigbluebot#1]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'i', 'bigbluebot' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData bigbluebot
8 silly fetchNamedPackageData bigbluebot
9 silly mapToRegistry name bigbluebot
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/bigbluebot
13 verbose request uri https://registry.npmjs.org/bigbluebot
14 verbose request no auth needed
15 info attempt registry request try #1 at 3:36:36 AM
16 verbose request id 94ec65bef98f8b5e
17 verbose etag W/"2c3847578ce254d1875d920e6d8d23fe"
18 verbose lastModified Wed, 15 Apr 2020 15:23:00 GMT
19 http request GET https://registry.npmjs.org/bigbluebot
20 http 304 https://registry.npmjs.org/bigbluebot
21 verbose headers { date: 'Tue, 02 Jun 2020 07:36:36 GMT',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'set-cookie': [ '__cfduid=d03cbc3ed4ceb7b67aaae5581d9d329a21591083396; expires=Thu, 02-Jul-20 07:36:36 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
21 verbose headers   'cf-ray': '59cf811b4cdf058d-LAX',
21 verbose headers   age: '217',
21 verbose headers   'cache-control': 'public, max-age=300',
21 verbose headers   etag: '"2c3847578ce254d1875d920e6d8d23fe"',
21 verbose headers   'last-modified': 'Wed, 15 Apr 2020 15:23:00 GMT',
21 verbose headers   vary: 'Accept-Encoding',
21 verbose headers   'cf-cache-status': 'HIT',
21 verbose headers   'cf-request-id': '03158f05110000058da992c200000001',
21 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
21 verbose headers   server: 'cloudflare' }
22 silly get cb [ 304,
22 silly get   { date: 'Tue, 02 Jun 2020 07:36:36 GMT',
22 silly get     connection: 'keep-alive',
22 silly get     'set-cookie': [ '__cfduid=d03cbc3ed4ceb7b67aaae5581d9d329a21591083396; expires=Thu, 02-Jul-20 07:36:36 GMT; path=/; domain=.npmjs.org; HttpOnly; SameSite=Lax' ],
22 silly get     'cf-ray': '59cf811b4cdf058d-LAX',
22 silly get     age: '217',
22 silly get     'cache-control': 'public, max-age=300',
22 silly get     etag: '"2c3847578ce254d1875d920e6d8d23fe"',
22 silly get     'last-modified': 'Wed, 15 Apr 2020 15:23:00 GMT',
22 silly get     vary: 'Accept-Encoding',
22 silly get     'cf-cache-status': 'HIT',
22 silly get     'cf-request-id': '03158f05110000058da992c200000001',
22 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
22 silly get     server: 'cloudflare' } ]
23 verbose etag https://registry.npmjs.org/bigbluebot from cache
24 verbose get saving bigbluebot to /root/.npm/registry.npmjs.org/bigbluebot/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly rollbackFailedOptional Starting
38 silly rollbackFailedOptional Finishing
39 silly runTopLevelLifecycles Starting
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 verbose stack Error: Refusing to install bigbluebot as a dependency of itself
42 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
42 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
42 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
42 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
42 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
43 verbose cwd /root/bigbluebot
44 error Linux 4.15.0-99-generic
45 error argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "bigbluebot"
46 error node v4.2.6
47 error npm  v3.5.2
48 error code ENOSELF
49 error Refusing to install bigbluebot as a dependency of itself
50 error If you need help, you may report this error at:
50 error     <https://github.com/npm/npm/issues>
51 verbose exit [ 1, true ]

**Comment by pedrobmarin** [comment]
Are you running node v4.2.6?

**Comment by aguerson** [comment]
Same problem ! :(
on ubuntu 18.04 lts
with node v8.10.0 and npm  v3.5.2

**Comment by aguerson** [comment]
Solved
In the package.json
change name bigbluebot with name bbbbot ( for example )
Regards,
Aurélien.
