### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by amguirado73** [mconf/bigbluebot#13]
Hi,

I have a server with 24 CPU's  Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz.

I can't create more than 40-50 bots. CPU's are 80-90%.

Is it normal?.

Thanks

**Comment by amguirado73** [comment]
The run file is:

let actions = async page => {
  await bigbluebot.audio.modal.listen(page)
}

**Comment by pedrobmarin** [comment]
Unfortunately it is. The HTML5 client is a heavy load even in a headless browser. In our load tests we run 10 to 20 16vCPU 30gRAM machines to get reliable results.
