### ISSUE TITLE
Timeout-Error: waiting for selector...

### ISSUE THREAD

**Issue by legrex** [mconf/bigbluebot#15]
Hi,

i have a strange problem, that i have no idea left to explain, so maybe some one can give a hint.
I installed bigbluebot on my home-workstation with a fresh Ubuntu 20.04-VM and have no problems, everything works
The same on a older Root-Server, it's a Debian Buster/Stable, everything works.

But since the ressources of these machines are very limited to get a reasonable number of bots, i clicked some EC2-Instances at Amazon. But regardless which OS i choose (tried, Debian Buster, Ubuntu 16.04 and 20.04 and Amazon Linux 2, seems to be a CentOS-Thing) i get timeout errors when i run nodejs run.js:

> `ERROR 	2020-10-04T16:38:10.432Z TimeoutError: waiting for selector `[aria-label^="Optionen"]` failed: timeout 180000ms exceeded
    at new WaitTask (/home/ec2-user/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:411:34)
    at DOMWorld.waitForSelector (/home/ec2-user/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:319:26)
    at Frame.waitForSelector (/home/ec2-user/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:842:51)
    at Page.waitForSelector (/home/ec2-user/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1322:33)
    at Object.join (/home/ec2-user/node_modules/bigbluebot/lib/util.js:128:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/ec2-user/node_modules/bigbluebot/lib/run.js:44:22
    at async Promise.all (index 0)
    at async /home/ec2-user/node_modules/bigbluebot/lib/run.js:57:7

You see i changed the timeout-variable in the config.json already to 18000ms from 6000ms, just to make sure it's not related somehow.

So all Bots stuck in the very first step:

> INFO 	2020-10-04T16:35:04.811Z Terence Dickinson: join https://bbbXXYY at Demo Meeting
INFO 	2020-10-04T16:35:05.400Z Garnett Watsica: join https://bbbXXYY at Demo Meeting
INFO 	2020-10-04T16:35:05.911Z Thelma Thiel: join https://bbbXXYY at Demo Meeting
INFO 	2020-10-04T16:35:06.418Z Ezekiel Lemke: join https://bbbXXYY at Demo Meeting
INFO 	2020-10-04T16:35:06.909Z Laurianne Reynolds: join https://bbbXXYY at Demo Meeting

The .env and run.js-files are copys from the other server/computers, where they run as expected.
To make things worse: If a choose test.bigbluebutton.org as bbb-Server, it runs as expected also in EC2. 

But i have no clue where to start with this ^ ^
Maybe someome have a idea. And mconf thanks for the software, i already had 60 Bots running with my both machines, which was nice to see in Grafana-Dasboard, how the BBB-Server behaves. Makes a lot of things easier in testing, of course! ;)

**Comment by pedrobmarin** [comment]
Looks like there is something different with your locale choice. The default language should be english but somehow you are fetching something else `[aria-label^="Optionen"]` (german?). Is this something you already used before?

Another thing to have in mind is that the bots run over a headless chromium instance and it needs some resources that normally UI-less machines don't provide out of the box (https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix)

**Comment by legrex** [comment]
Thanks for that quick reaction!

Indeed the installation of BBB is german by default, but it does not look like it interferes with bigbluebot.

On my local VM-bigbluebot it looks like this:

> INFO 	2020-10-04T19:11:34.936Z Bots: 36
INFO 	2020-10-04T19:11:34.937Z Life: 600000 seconds
INFO 	2020-10-04T19:11:34.937Z Creating meeting
INFO 	2020-10-04T19:11:35.094Z Fetching EN locale
INFO 	2020-10-04T19:11:47.300Z Cassie Herzog: join https://XYZ.tld at Demo Meeting
DEBUG 	2020-10-04T19:11:50.085Z Cassie Herzog: notice [aria-label^="Optionen"]
DEBUG 	2020-10-04T19:11:52.092Z Cassie Herzog: [aria-label^="Audioteilnahmedialog"] is visible
DEBUG 	2020-10-04T19:11:52.092Z Cassie Herzog: skip audio join
INFO 	2020-10-04T19:11:52.092Z Cassie Herzog: perform audio modal microphone
DEBUG 	2020-10-04T19:11:52.092Z Cassie Herzog: click [aria-label^="Mit Mikrofon"]
DEBUG 	2020-10-04T19:11:54.120Z Cassie Herzog: click [aria-label^="Echo ist hörbar"]
INFO 	2020-10-04T19:11:59.300Z Elyssa Schmeler: join https://XYZ.tld at Demo Meeting
DEBUG 	2020-10-04T19:12:01.055Z Cassie Herzog: [aria-label^="Audio beenden"] is visible
PASS 	2020-10-04T19:12:01.055Z Cassie Herzog: audio modal microphone
DEBUG 	2020-10-04T19:12:01.836Z Elyssa Schmeler: notice [aria-label^="Optionen"]
DEBUG 	2020-10-04T19:12:03.841Z Elyssa Schmeler: [aria-label^="Audioteilnahmedialog"] is visible
DEBUG 	2020-10-04T19:12:03.841Z Elyssa Schmeler: skip audio join
INFO 	2020-10-04T19:12:03.841Z Elyssa Schmeler: perform audio modal microphone
DEBUG 	2020-10-04T19:12:03.841Z Elyssa Schmeler: click [aria-label^="Mit Mikrofon"]
DEBUG 	2020-10-04T19:12:05.869Z Elyssa Schmeler: click [aria-label^="Echo ist hörbar"]
INFO 	2020-10-04T19:12:11.303Z Linnie Breitenberg: join https://XYZ.tld at Demo Meeting
DEBUG 	2020-10-04T19:12:12.785Z Elyssa Schmeler: [aria-label^="Audio beenden"] is visible
PASS 	2020-10-04T19:12:12.785Z Elyssa Schmeler: audio modal microphone

(Even with fetching EN locale)

I installed all the dependencies for puppeteer on the respective machines..

**Comment by pedrobmarin** [comment]
Hmm, that's weird. Could you try changing this to DE https://github.com/mconf/bigbluebot/blob/666a3396ae10c9a9bb0aacfa49735bf5a8f15b9e/config/config.json#L36?

**Comment by pedrobmarin** [comment]
This file will be in the node_modules/bigbluebot dir

**Comment by legrex** [comment]
I tried this before. Did not help. But now it works though: I changed the locale in meteor-settings to hard "en", so that bbb is ignoring the browser-settings. Now bigbluebot works also on the AWS-Instance. I mean i do not really understand _why_, but for this moment it's is solved for me! Thanks for your hint!

**Comment by pedrobmarin** [comment]
Yeah, in the meantime I figured it wouldn't help because the bot was already fetching for the correct locale.

Could you let this issue open? I'll try to give this some extra thought. I think I already assisted someone that was having a similar locale issue.

**Comment by pedrobmarin** [comment]
Fixed some language issues here #17 . Maybe solved this problem.
