### ISSUE TITLE
ERROR WHILE USING npm i bigbluebot

### ISSUE THREAD

**Issue by Ryan-samaeian** [mconf/bigbluebot#18]
HI i get an err when i run npm i bigbluebot

**Comment by pedrobmarin** [comment]
Could you share any more details about it?

**Comment by georgethegreatat** [comment]
Hello. I have a problem with bbbot.
I successfully installed bbb 2.2.30 on my server and bbb-demo. Test it (working). 
But when I try to run it, BBBot creating the meeting on the server but there are no Participants online, so I can not test my server. 
Using Ubuntu 18.04 for test server and 16.04 for bbb.
