### ISSUE TITLE
BigBlueBot issue

### ISSUE THREAD

**Issue by georgethegreatat** [mconf/bigbluebot#19]
Hello everyone.
I just installed bbbot and tried to test it but i'm stack now on this.
Seems like all working fine but no users connected to the conference. Meeting has been created through the bbbot, but no one there. Could you help me please ?

**Comment by aguerson** [comment]
Sorry, bbb  bot version is not the same as mine.

Mine is ok
https://github.com/mconf/bigbluebot/issues/14

Try to get the old version, and not the new.
I have not test with the update yet.

**Comment by georgethegreatat** [comment]
@aguerson 
Hello, which version are you using ?

**Comment by pedrobmarin** [comment]
Did you follow the README instructions? Could you take an extra look there to check if something went missing?
Are there any logs? (they might be content sensitive, so I would verify on that before sharing)

**Comment by georgethegreatat** [comment]
Hi @pedrobmarin 

root@georgethegreat:/home/george# node run.js
INFO    2020-12-09T12:41:32.242Z Bots: 5
INFO    2020-12-09T12:41:32.244Z Life: 60 seconds
INFO    2020-12-09T12:41:32.244Z Creating meeting
INFO    2020-12-09T12:41:32.707Z Fetching en locale
DEBUG   2020-12-09T12:41:33.120Z Opening browser
DEBUG   2020-12-09T12:41:35.124Z Opening browser
DEBUG   2020-12-09T12:41:37.125Z Opening browser
DEBUG   2020-12-09T12:41:39.126Z Opening browser
DEBUG   2020-12-09T12:41:41.127Z Opening browser

As you can see this opening browser but nothing happening.

**Comment by pedrobmarin** [comment]
Ok. I think I got it: `IMPORTANT: do not run this lib with root privileges`

**Comment by georgethegreatat** [comment]
Fixed, thanks.
