### ISSUE TITLE
Application Stuck on Startup

### ISSUE THREAD

**Issue by murat-cileli** [mconf/bigbluebot#2]
Hello. 
When I start the application, it's appear stuck on this phase below. (BigBlueButton v2.2.20)

![image](https://user-images.githubusercontent.com/6532000/87651428-9260f300-c75b-11ea-89ac-80d6303da3b2.png)

INFO 	2020-07-16T08:53:46.937Z Bots: 1
INFO 	2020-07-16T08:53:46.940Z Life: 600 seconds
INFO 	2020-07-16T08:53:46.941Z Creating room
INFO 	2020-07-16T08:53:47.035Z Fetching EN locale

**Comment by pedrobmarin** [comment]
Hi @murat-cileli .

I see you changed the default configurations at least increasing the bot's life span. Did you also increased the bot's wait value? Are you able to run the bot against an official server? Could you try https://test.bigbluebutton.org?

**Comment by pedrobmarin** [comment]
Looks like this was resolved. I'll be closing this issue.
