### ISSUE TITLE
BigBlueBot trips over locales missing in BigBlueButton 2.3+

### ISSUE THREAD

**Issue by antobinary** [mconf/bigbluebot#22]
BigBlueBot starting against BigBlueButton 2.3-beta1+ server fails to obtain locale json, and trips over early into running.

I checked against a BigBlueButton 2.2.35+ and all is fine

on 2.3-beta-1 I get

```
$ node index.js 
INFO 	2021-03-31T16:58:44.017Z Bots: 1
INFO 	2021-03-31T16:58:44.018Z Life: 60 seconds
INFO 	2021-03-31T16:58:44.018Z Creating meeting
INFO 	2021-03-31T16:58:44.468Z Fetching en_CA:en locale
INFO 	2021-03-31T16:58:44.468Z URL = https://test23.bigbluebutton.org/html5client/locale?locale=en_CA:en
ERROR 	2021-03-31T16:58:44.609Z Missing locale messages
INFO 	2021-03-31T16:58:46.892Z Juston Schumm: join https://test23.bigbluebutton.org at Demo Meeting
ERROR 	2021-03-31T16:58:48.818Z TypeError: Cannot read property 'app.navBar.settingsDropdown.optionsLabel' of undefined
    at localize (/home/anton/dev/run_bbbot_locally/node_modules/bigbluebot/lib/util.js:106:41)
    at translate (/home/anton/dev/run_bbbot_locally/node_modules/bigbluebot/lib/util.js:113:24)
    at Object.join (/home/anton/dev/run_bbbot_locally/node_modules/bigbluebot/lib/util.js:146:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/anton/dev/run_bbbot_locally/node_modules/bigbluebot/lib/run.js:49:22
    at async Promise.all (index 0)
    at async /home/anton/dev/run_bbbot_locally/node_modules/bigbluebot/lib/run.js:61:7
    at async Promise.all (index 0)
    at async Object.run (/home/anton/dev/run_bbbot_locally/node_modules/bigbluebot/lib/run.js:81:3)
```

https://github.com/mconf/bigbluebot/blob/master/lib/util.js#L245-L250

This is the relative change in BigBlueButton (afaik)
2.3: https://github.com/bigbluebutton/bigbluebutton/blob/develop/bigbluebutton-html5/imports/startup/client/intl.jsx#L64-L140
2.2: https://github.com/bigbluebutton/bigbluebutton/blob/v2.2.x-release/bigbluebutton-html5/imports/startup/client/intl.jsx#L149-L173

2.3:
![Screenshot from 2021-03-31 14-20-58](https://user-images.githubusercontent.com/6312397/113207456-a479b780-923e-11eb-99e1-10ee41440076.png)

2.2:
![Screenshot from 2021-03-31 14-20-00](https://user-images.githubusercontent.com/6312397/113207458-a479b780-923e-11eb-8f83-507f1c6d71ef.png)

**Comment by pedrobmarin** [comment]
Fixed in https://github.com/mconf/bigbluebot/commit/f0cfcdae6211a87dd16b0208a297e8f008baa2fe
