### ISSUE TITLE
Cant join audio/video

### ISSUE THREAD

**Issue by jonnyfux** [mconf/bigbluebot#34]
Hi,
I was running the basic example from within the project (https://github.com/mconf/bigbluebot/blob/master/example.js). The tool also logs that it joins but if I run the Test in non-headless mode I can see that the virtual user is not joining the audio. I tried the same for video and still nothing 

NFO    2021-08-31T10:23:46.284Z Bots: 1
INFO    2021-08-31T10:23:46.286Z Life: 60 seconds
INFO    2021-08-31T10:23:46.286Z Creating meeting
INFO    2021-08-31T10:23:46.444Z Fetching en locale
INFO    2021-08-31T10:23:48.828Z Bertram McCullough: join URL at Demo Meeting

**Comment by pedrobmarin** [comment]
Hi,

Could you provide more information regarding your BigBlueButton setup? Things like version you are running and settings that deviate from the default package installation can impair the bot's ability to identify the UI.

**Comment by jonnyfux** [comment]
Sure, 
I'm running BBB Version 2.3.12 and it was installed with the bbb install script with the standard settings. The UI should be identical to the standard (see screenshot) 
![grafik](https://user-images.githubusercontent.com/58081454/131497318-e319d985-0271-4470-804d-d18088ec113d.png)

**Comment by pedrobmarin** [comment]
- are you able to identify any errors at the bot's browser console?
- could you re-run your script with the bot's log elevated to "debug"?

**Comment by jonnyfux** [comment]
no errors in the chrome console

Debug Log: 
INFO    2021-08-31T11:58:41.258Z Bots: 1
INFO    2021-08-31T11:58:41.259Z Life: 60 seconds
INFO    2021-08-31T11:58:41.259Z Creating meeting
INFO    2021-08-31T11:58:41.414Z Fetching en locale
DEBUG   2021-08-31T11:58:41.487Z Fetching en fallback locale
DEBUG   2021-08-31T11:58:41.610Z Fetching en normalized locale
DEBUG   2021-08-31T11:58:41.736Z Opening browser
INFO    2021-08-31T11:58:43.796Z Jeramie Wuckert: join URL at Demo Meeting
DEBUG   2021-08-31T11:58:45.502Z Jeramie Wuckert: notice [aria-label^="Options"]

**Comment by pedrobmarin** [comment]
Are you able to identify this button at your BigBlueButton:

![options](https://user-images.githubusercontent.com/1778398/131499469-4f3b6098-e2ec-406c-b900-46e58d1d9023.png)

Detail at the `aria-label="Options"`, the selector the bot is not being able to find

**Comment by jonnyfux** [comment]
Ah i see my version is apparently in german (did not know I could change this) it says aria-label="Optionen". Any way of changing the selector in my version?

**Comment by pedrobmarin** [comment]
Hmmm, that's something I've not being testing in a while but you could try setting the bot's browser locale to german at https://github.com/mconf/bigbluebot/blob/a53b0dc47026cf6382d3b873494d8782ce899a33/config/config.json#L38
Not sure if it's going to work tho because puppeteer (the automation lib behind this scripts) runs a headless chromium that ships english by default.

**Comment by pedrobmarin** [comment]
Another thing that you could try is using the userdata `bbb_override_default_locale` at your bot script to set it to `en` to match the headless browser. It would look like this:

```
const bigbluebot = require('bigbluebot');

const actions = async page => {
  await bigbluebot.audio.modal.microphone(page);
  await bigbluebot.video.join(page);
  await bigbluebot.chat.send(page);
};

const options = {
  host: 'https://your.bigbluebutton.server', // change to your server
  secret: 'yourbigbluebuttonsecret', // change to your secret
  version: '2.3',
  room: 'yourbigbluebuttonroomidentifier', // change to your room
  password: {
    moderator: 'yourmoderatorpassword', // change to the passwords that you need
    attendee: 'yourattendeepassword', // same as above
  },
  moderator: true OR false, // anything you like here
  userdata: {
    "userdata-bbb_override_default_locale": "en",
  },
};

bigbluebot.run(actions, options);
```

**Comment by jonnyfux** [comment]
Awesome, thank you! 

Setting   "userdata-bbb_override_default_locale": "ger", solved the issue!

**Comment by jonnyfux** [comment]
Soory for reopening the issue. I just tried the same setup on an AWS EC2 Instance and it is again stuck. 

Debugging: 
INFO 	2021-08-31T14:02:13.301Z Bots: 1
INFO 	2021-08-31T14:02:13.302Z Life: 60 seconds
INFO 	2021-08-31T14:02:13.302Z Creating meeting
INFO 	2021-08-31T14:02:13.361Z Fetching en locale
DEBUG 	2021-08-31T14:02:13.365Z Fetching en fallback locale
DEBUG 	2021-08-31T14:02:13.370Z Fetching en normalized locale
DEBUG 	2021-08-31T14:02:13.376Z Opening browser

I first thought the Chrome browser is now back to default and in English and changed everything back to default: 

`const bigbluebot = require('bigbluebot');

const actions = async page => {
  await bigbluebot.video.join(page);
};` 

But that did not help. Any ideas?

**Comment by pedrobmarin** [comment]
Hmmm, I might know what's the problem...

Some GUI-less machines need extra packages to be able to run a headless browser. Try checking this out https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix or even https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-aws-ec2-instance-running-amazon-linux

**Comment by jonnyfux** [comment]
Thanks for the links, although they did not solve the problem (instead they returned a 'command not found') they directed me to the right path, I think :D  
I solved it by adding those commands
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          apt install ./google-chrome-stable_current_amd64.deb -y

And adding this: BIGBLUEBOT_BROWSER=/usr/bin/google-chrome-stable

However it still not works out of the AWS cloud-init script but if I do it manually it works. 

The cloud-init-output.log yields: 
INFO    2021-09-01T06:44:08.257Z Bots: 1
INFO    2021-09-01T06:44:08.258Z Life: 60 seconds
INFO    2021-09-01T06:44:08.258Z Creating meeting
INFO    2021-09-01T06:44:08.349Z Fetching en locale
^[[34mDEBUG^[[0m        2021-09-01T06:44:08.353Z Fetching en fallback locale
^[[34mDEBUG^[[0m        2021-09-01T06:44:08.359Z Fetching en normalized locale
^[[34mDEBUG^[[0m        2021-09-01T06:44:08.363Z Opening browser

**Comment by jonnyfux** [comment]
I just double checked and its not working if executed as a script...

**Comment by jonnyfux** [comment]
Ok once again closing this, soory for wasting your time. 

AWS is launching the script as root, since this is not supported by bigbluebot it fails. 

I found a workaround starting my node file as non-root by using this command: sudo -u ubuntu node stress.js

I still think it should not fail silently. Anyway the issue was on my side, thank for your support :)

**Comment by pedrobmarin** [comment]
> I still think it should not fail silently

Agreed. Not the first time folks get in trouble because of this puppeteer sandbox protection.

Added a check on run to abort root users https://github.com/mconf/bigbluebot/commit/15b5756e5b7dcb339d98878f0e52465e06ce886e
