### ISSUE TITLE
Stuck on Fetching EN locale

### ISSUE THREAD

**Issue by ryprfpryr** [mconf/bigbluebot#4]
The one only value used in .env:

```
# BigBlueButton hostname
BIGBLUEBOT_HOST=https://test.bigbluebutton.org
```

Using Node 12.18.3 [NPM v6.14.6] (also tried with 10.22.0)

Tested with run.js:

```
const bigbluebot = require('bigbluebot')

let actions = async page => {
  // H.264 users must use an external Chrome instance
  await bigbluebot.video.join(page)
}

bigbluebot.run(actions)
```

Maybe related to #2

**Comment by pedrobmarin** [comment]
I made a fresh install and had no problems on that server. Could you run yours outside headless mode? There's an option inside `node_modules/bigbluebot/config/config.json`

**Comment by ryprfpryr** [comment]
Changed "headless": true to false

`  "browser": {
    "headless": false,
    "endpoint": null,`

Same output.

**Comment by pedrobmarin** [comment]
It's not the output that matter, it's everything else you get from the browser debug tools: console, network... even the screen. In what point you bot got stuck?

**Comment by ryprfpryr** [comment]
This is what I get:

~/node_modules/bigbluebot# node run.js
INFO 	2020-08-15T17:52:25.688Z Bots: 1
INFO 	2020-08-15T17:52:25.690Z Life: 60 seconds
INFO 	2020-08-15T17:52:25.690Z Fetching EN locale

This is the same output for test.bigbluebutton.org and one of my bbb servers.

If I set my BBB host + BBB key, I can see the meeting is created but the bots are not able to access.

**Comment by pedrobmarin** [comment]
When you run it without headless you supposed to get a chromium browser up. Can you collect logs from that browser?

Using with a secret key you need to have the html5 client as default at your bbb-web properties? It's configured here https://github.com/bigbluebutton/bigbluebutton/blob/dc0fc459e2a9c5917e2812ae96eeb1a71ff52693/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L247

**Comment by ryprfpryr** [comment]
> When you run it without headless you supposed to get a chromium browser up. Can you collect logs from that browser?

How should I do that?

> Using with a secret key you need to have the html5 client as default at your bbb-web properties? It's configured here https://github.com/bigbluebutton/bigbluebutton/blob/dc0fc459e2a9c5917e2812ae96eeb1a71ff52693/bigbluebutton-web/grails-app/conf/bigbluebutton.properties#L247

This is ok, I am using a fresh BBB install.

I have already tried bigbluebot on the same BBB server, and several others Ubuntu 18.04 servers, also 16.04, etc etc. Always the same: it gets stuck in Fetching EN locale

**Comment by pedrobmarin** [comment]
Are you running the bots on a machine that has a GUI? Are you able to run a browser at the machine you deployed the bot lib?

**Comment by ryprfpryr** [comment]
Yes I have installed it and testing on my local Ubuntu 18.04 with GUI

**Comment by pedrobmarin** [comment]
So does it pops a browser when you runs it headless: false?

**Comment by ryprfpryr** [comment]
No, it doesn't

**Comment by pedrobmarin** [comment]
When you ran `npm i bigbluebot`, did it downloaded a chromium instance?

**Comment by ryprfpryr** [comment]
Yes

**Comment by pedrobmarin** [comment]
Try running this puppeteer example:
```
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({headless: false})
    const page = await browser.newPage()
    await page.setViewport({ width: 1280, height: 800 })
    await page.goto('https://www.nytimes.com/')
    await page.screenshot({ path: 'nytimes.png', fullPage: true })
    await browser.close()
})()
```

**Comment by ryprfpryr** [comment]
(node:11238) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[11249:11249:0815/191317.939144:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/root/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/root/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:327:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:11238) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11238) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pedrobmarin** [comment]
Hmmm, looks like the problem is the root user.

Open this file `node_modules/bigbluebot/lib/pool.js` and add a `--no-sandbox` in here https://github.com/mconf/bigbluebot/blob/01e20e483b7c3445ecefbf60f9d8fb871df93f04/lib/pool.js#L7-L13

**Comment by ryprfpryr** [comment]
Now Chromium is popping up, but it just pops up for a second, disappears, and pops up again, and repeats in an infinite loop (see gif below): 

![Aug-15-2020 8-16-22 PM](https://user-images.githubusercontent.com/68156081/90323194-3f35b800-df34-11ea-9255-e3b317e35daa.gif)

**Comment by ryprfpryr** [comment]
UPDATE: I switched back 

`"browser": { "headless": false, "endpoint": null,`

And now seems to be working! 

It seems the main reason was addin this line at Line nº 13 in node_modules/bigbluebot/lib/pool.js :

``--no-sandbox`,`

Thank you @pedrobmarin !

**Comment by ryprfpryr** [comment]
UPDATE2: Now trying on Ubuntu 16.04 server (no GUI), with the same tweaks but same output as before! Just stuck at Fetching EN locale 😓

**Comment by pedrobmarin** [comment]
I recommend to run outside root since Chrome has it's security measures. I'll add this to the documentation

**Comment by ryprfpryr** [comment]
> I recommend to run outside root since Chrome has it's security measures. I'll add this to the documentation

Yes indeed, it is solved by just running bigbluebot from other user than root. 

I am getting some errors when I try to use audio join:

```
~/node_modules/bigbluebot$ node qwe.js
INFO 	2020-08-16T00:41:01.665Z Bots: 1
INFO 	2020-08-16T00:41:01.667Z Life: 1000000 seconds
INFO 	2020-08-16T00:41:01.668Z Creating room
INFO 	2020-08-16T00:41:01.921Z Fetching EN locale
INFO 	2020-08-16T00:41:04.155Z Gabriel Gislason: join https://b1.aulanube.com.ar at testt
INFO 	2020-08-16T00:41:09.149Z Gabriel Gislason: perform audio modal microphone
ERROR 	2020-08-16T00:42:11.195Z TimeoutError: waiting for selector "[aria-label^="Echo is audible"]" failed: timeout 60000ms exceeded
    at new WaitTask (/home/p/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:394:34)
    at DOMWorld._waitForSelectorOrXPath (/home/p/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:326:26)
    at DOMWorld.waitForSelector (/home/p/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:309:21)
    at Frame.waitForSelector (/home/p/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:801:51)
    at Page.waitForSelector (/home/p/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1215:33)
    at Object.click (/home/p/node_modules/bigbluebot/lib/util.js:130:16)
    at Object.execute (/home/p/node_modules/bigbluebot/lib/action/audio.js:21:20)
    at async perform (/home/p/node_modules/bigbluebot/lib/action/perform.js:30:5)
    at async Object.microphone (/home/p/node_modules/bigbluebot/lib/action/audio.js:67:31)
    at async actions (/home/p/node_modules/bigbluebot/qwe.js:3:3)
```

Inside "qwe.js":

`const bigbluebot = require('bigbluebot')

let actions = async page => {
  await bigbluebot.audio.modal.listen(page)
}

bigbluebot.run(actions)`

**Comment by ryprfpryr** [comment]
> I recommend to run outside root since Chrome has it's security measures. I'll add this to the documentation

Yes indeed, it is solved by just running bigbluebot from other user than root. 

I am getting some errors when I try to use audio join:

```
~/node_modules/bigbluebot$ node qwe.js
INFO 	2020-08-16T00:41:01.665Z Bots: 1
INFO 	2020-08-16T00:41:01.667Z Life: 1000000 seconds
INFO 	2020-08-16T00:41:01.668Z Creating room
INFO 	2020-08-16T00:41:01.921Z Fetching EN locale
INFO 	2020-08-16T00:41:04.155Z Gabriel Gislason: join https://test.bbbserver.com at TESTROOM
INFO 	2020-08-16T00:41:09.149Z Gabriel Gislason: perform audio modal microphone
ERROR 	2020-08-16T00:42:11.195Z TimeoutError: waiting for selector "[aria-label^="Echo is audible"]" failed: timeout 60000ms exceeded
    at new WaitTask (/home/p/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:394:34)
    at DOMWorld._waitForSelectorOrXPath (/home/p/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:326:26)
    at DOMWorld.waitForSelector (/home/p/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:309:21)
    at Frame.waitForSelector (/home/p/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:801:51)
    at Page.waitForSelector (/home/p/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1215:33)
    at Object.click (/home/p/node_modules/bigbluebot/lib/util.js:130:16)
    at Object.execute (/home/p/node_modules/bigbluebot/lib/action/audio.js:21:20)
    at async perform (/home/p/node_modules/bigbluebot/lib/action/perform.js:30:5)
    at async Object.microphone (/home/p/node_modules/bigbluebot/lib/action/audio.js:67:31)
    at async actions (/home/p/node_modules/bigbluebot/qwe.js:3:3)
```

Inside "qwe.js":

`const bigbluebot = require('bigbluebot')

let actions = async page => {
  await bigbluebot.audio.modal.listen(page)
}

bigbluebot.run(actions)`
