### ISSUE TITLE
Unable to use bigbluebot

### ISSUE THREAD

**Issue by mrFarno** [mconf/bigbluebot#5]
Hello, 

I'm trying to use Bigbluebot in order to stress test a Bigbluebutton server. In my .env file are the required parameters (hostname, API key from "bbb-conf --secret" command) and my run.js file is : 
_const bigbluebot = require('bigbluebot')

let actions = async page => {
  await bigbluebot.audio.modal.listen(page)
}

bigbluebot.run(actions)_

When I run "node run.js" my console only display the following : 
INFO    2020-08-28T10:04:30.591Z Bots: 5
INFO    2020-08-28T10:04:30.593Z Life: 60 seconds
INFO    2020-08-28T10:04:30.594Z Creating room
INFO    2020-08-28T10:04:30.967Z Fetching EN locale
 
Nothing else is happening.
I tried using bigbluebot (v1.3.5) in Windows 10 and inside a container running ubuntu 16.04 with no results.

My log level is set as "debug"

Maybe I misunderstood something !

Thanks

**Comment by pedrobmarin** [comment]
Hi.

Check if this helps you out https://github.com/mconf/bigbluebot/issues/4

Em sex, 28 de ago de 2020 07:19, mrFarno <notifications@github.com>
escreveu:

**Comment by mrFarno** [comment]
It worked ! It seemed that somehow Chromium download failed during installation, I figured it out by setting headless parameter to false. I did a fresh install and now it work.

Thank you very much and sorry for the bother !
