### ISSUE TITLE
Close created rooms

### ISSUE THREAD

**Issue by mittler-works** [mconf/bigbluebot#8]
If a room was created by bigbluebot, it should be closed after testing.

**Comment by pedrobmarin** [comment]
BigBlueButton normally closes empty rooms after a minute or two. Are you thinking about a more immediate action?

**Comment by mittler-works** [comment]
The time after which a room is closed at BBB is adjustable. Since we have lectures with breaks, etc. at the university and the rooms should also survive breaks (because of chat, shared notes, etc.), we have set our instances to 180 minutes.

When we simulated small groups with BigBlueBots, we then had hundreds of open rooms that were not closed.

I'll just prepare an MR for this issue, then you can check it out to see if you find it useful :relaxed:
