### ISSUE TITLE
Create rooms with random ids

### ISSUE THREAD

**Issue by mittler-works** [mconf/bigbluebot#9]
Small groups cannot be tested (e.g. 50 rooms with only 5 participants each). If I run the script 50 times, all participants end up in the same room. If we randomly generate the room ID, we can also test such scenarios.

**Comment by pedrobmarin** [comment]
You can also export your `env` property at your scripts.

If I'm not mistaken, something like this should work:
```
#!/bin/bash

for i in {1..50}
do
  export BIGBLUEBOT_ROOM="Room $i"
  node bot-script.js
done
```

But you will notice each bot will have to open a headless browser tab and will consume a lot of your machine resources. So normally such test scenarios will demand more than one machine dispatching bots.

**Comment by mittler-works** [comment]
Ah cool, the environment is a good trick. I had done it temporarily with a random generator in conf.js.
Just a simple approach as:
`custom.url.meeting.name = BIGBLUEBOT_ROOM ? BIGBLUEBOT_ROOM: uid(40);`

I just wanted to provide an MR, but if it works like that with the environment, the MR is probably unnecessary :joy: 

>So normally such test scenarios will demand more than one machine dispatching bots.

Yep. we're testing a BBB cluster at the University of Applied Science, Mittelhessen and have spawned the bots with 51 VMs. Just works fine :)
When the load tests are done, I'll post a link with the results here :+1:

**Comment by pedrobmarin** [comment]
> Yep. we're testing a BBB cluster at the University of Applied Science, Mittelhessen and have spawned the bots with 51 VMs. Just works fine :)
> When the load tests are done, I'll post a link with the results here +1

Oh, cool. Could you also share your results at bigbluebutton's dev mailing list https://groups.google.com/g/bigbluebutton-dev? Folks there love these numbers.
